"""remove encrypt password add leaderboard_opt_in

Revision ID: 1eea8ed3b1c3
Revises: f84f1d118027
Create Date: 2026-09-04 19:39:08.860056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eea8ed3b1c3'
down_revision: Union[str, Sequence[str], None] = 'f84f1d118027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('leaderboard_opt', sa.Boolean(), server_default="false", nullable=False))
    op.drop_column('attendance', 'encrypted_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'leaderboard_opt')
    # ### end Alembic commands ###
