"""add sem and branch columns

Revision ID: 2cb1ff78c9a4
Revises: 1eea8ed3b1c3
Create Date: 2026-09-04 23:20:26.288008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb1ff78c9a4'
down_revision: Union[str, Sequence[str], None] = '1eea8ed3b1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('sem', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('branch', sa.String(), nullable=True))
    op.alter_column('attendance', 'leaderboard_opt',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'leaderboard_opt',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('attendance', 'branch')
    op.drop_column('attendance', 'sem')
    # ### end Alembic commands ###
