"""donation admin_note

Revision ID: 34f42079fe9b
Revises: c9f4b1a7d253
Create Date: 2026-09-30 21:56:41.698713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f42079fe9b'
down_revision: Union[str, Sequence[str], None] = 'c9f4b1a7d253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('admin_note', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'admin_note')
    # ### end Alembic commands ###
