"""modified usn to encrpyted_usn and added encrypted_password

Revision ID: 53d8362a539b
Revises: 86fc43f7e825
Create Date: 2026-09-01 20:35:33.917131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53d8362a539b'
down_revision: Union[str, Sequence[str], None] = '86fc43f7e825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('encypted_usn', sa.String(), nullable=False))
    op.add_column('attendance', sa.Column('encypted_password', sa.String(), nullable=False))
    op.alter_column('attendance', 'absent_periods',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('attendance', 'usn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('usn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('attendance', 'absent_periods',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('attendance', 'encypted_password')
    op.drop_column('attendance', 'encypted_usn')
    # ### end Alembic commands ###
