"""add request_left column

Revision ID: 6c01139595d9
Revises: 2cb1ff78c9a4
Create Date: 2026-09-07 21:59:09.249125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c01139595d9'
down_revision: Union[str, Sequence[str], None] = '2cb1ff78c9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('request_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'request_left')
    # ### end Alembic commands ###
