"""create attendance table

Revision ID: 86fc43f7e825
Revises: 
Create Date: 2026-09-01 20:02:53.374128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86fc43f7e825'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('usn', sa.String(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('absent_periods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_avg', sa.Float(), nullable=True),
    sa.Column('can_miss85', sa.Integer(), nullable=True),
    sa.Column('can_miss75', sa.Integer(), nullable=True),
    sa.Column('need_to_attend85', sa.Integer(), nullable=True),
    sa.Column('need_to_attend75', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('usn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
