"""fix encrypted column name

Revision ID: f84f1d118027
Revises: ffd4ea84aa31
Create Date: 2026-09-02 20:05:41.968758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84f1d118027'
down_revision: Union[str, Sequence[str], None] = 'ffd4ea84aa31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('encrypted_password', sa.String(), nullable=False))
    op.drop_column('attendance', 'encypted_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('encypted_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('attendance', 'encrypted_password')
    # ### end Alembic commands ###
