"""add timetable column

Revision ID: fb7ba62ec104
Revises: 9d3a7c2e6b10
Create Date: 2026-09-29 19:12:18.065160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb7ba62ec104'
down_revision: Union[str, Sequence[str], None] = '9d3a7c2e6b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('timetable', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'timetable')
    # ### end Alembic commands ###
