"""renamed encrypted_usn to usn

Revision ID: ffd4ea84aa31
Revises: 53d8362a539b
Create Date: 2026-09-02 19:20:49.435149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffd4ea84aa31'
down_revision: Union[str, Sequence[str], None] = '53d8362a539b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('usn', sa.String(), nullable=False))
    op.alter_column('attendance', 'summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('attendance', 'encypted_usn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('encypted_usn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('attendance', 'summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('attendance', 'usn')
    # ### end Alembic commands ###
